// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextWindowCategory } from "./ThreadContextWindowCategory";
import type { ThreadContextWindowTarget } from "./ThreadContextWindowTarget";

export type ThreadContextWindowComponent = { id: string, category: ThreadContextWindowCategory, source: string, label: string, target: ThreadContextWindowTarget, mappingConfidence: ThreadContextWindowMappingConfidence | null, assemblyStepIds: Array<string>, estimatedTokens: number, estimatedBytes: number, contentHash: string, value: unknown, };
