// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextWindowComponent } from "./ThreadContextWindowComponent";
import type { ThreadContextWindowSegment } from "./ThreadContextWindowSegment";

export type ThreadContextWindowBreakdown = { modelContextWindow: number | null, reportedInputTokens: number | null, estimatedTotalTokens: number, segments: Array<ThreadContextWindowSegment>, components: Array<ThreadContextWindowComponent>, };
