// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextWindowCategory } from "./ThreadContextWindowCategory";

export type ThreadContextWindowSegment = { category: ThreadContextWindowCategory, label: string, estimatedTokens: number, estimatedBytes: number, percentOfReportedInput: number | null, };
