// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadContextWindowCategory = "model_scaffold" | "tool_schemas" | "runtime_context" | "project_user_context" | "conversation" | "tool_io" | "model_state" | "other";
